// SPDX-License-Identifier: GPL-3.0-only
//! The render graph.
//!
//! A render is a pure function of a project and an instant (R-4.1), and this
//! is the shape that makes it one: a graph of tasks with typed inputs, no
//! ambient state, and no way to observe when anything ran.
//!
//! Two invariants are structural rather than checked. A node may only refer to
//! nodes added before it, so **a cycle is unrepresentable** — there is no
//! `add_edge` to get wrong and no validation pass to forget. And every node's
//! identity is a digest over its kind, its parameters and its inputs'
//! identities, so two nodes that would compute the same picture *are* the same
//! node as far as the cache is concerned (R-8.5).
//!
//! Sapote is single-core, so this evaluates serially today. It is written as
//! though it did not: nothing here depends on evaluation order, and the tests
//! prove that by evaluating the same graph in every order a scheduler could
//! choose and comparing the results (R-6.2). The day cores arrive, nothing in
//! this model changes.

use alloc::vec::Vec;

use sapstudio_core::{Digest, Rational, Sha256};
use sapstudio_media::{
    AlphaState, CacheKey, ColourDescription, Frame, FrameDescription, FramePool, TestPattern,
};

use crate::composite;
use crate::convert;
use crate::status::{RenderStatus, Result};

/// How many nodes one graph may hold.
///
/// A policy bound. A render graph for a frame of a timeline is tens of nodes;
/// one that reaches this has been generated by a loop that meant to stop.
pub const MAX_NODES: usize = 4096;

/// A reference to a node in a graph.
///
/// It is an index, and it is only ever handed out by [`Graph::add`] for a node
/// that already exists, which is what makes forward references — and therefore
/// cycles — impossible to write.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct NodeId(usize);

impl NodeId {
    /// Where in the graph this node sits.
    #[must_use]
    pub const fn index(self) -> usize {
        self.0
    }

    /// Build an identifier from an index, for tests that need to name a node
    /// that does not exist.
    ///
    /// Deliberately awkward to reach for: every identifier a caller should
    /// have comes from [`Graph::add`], and one built here is exactly the thing
    /// the graph is supposed to refuse.
    #[must_use]
    pub const fn from_index_for_test(index: usize) -> Self {
        Self(index)
    }
}

/// One step of a render.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Node {
    /// A frame drawn from nothing, which is what a generator is.
    Pattern {
        /// What to draw.
        pattern: TestPattern,
        /// What the result is.
        description: FrameDescription,
    },
    /// A frame of a single value.
    Blank {
        /// What the result is.
        description: FrameDescription,
    },
    /// A frame of media, named by what that media *is*.
    ///
    /// By content digest rather than by any project's identifier for it,
    /// because that is what makes a cached frame usable: the same footage in
    /// two projects is the same footage, and a node that named it by a
    /// project-local index would cache it twice and could never tell that the
    /// file had been swapped underneath.
    ///
    /// Where the frame comes from is a [`Media`], because a graph knows how to
    /// combine frames and nothing about where they live.
    Source {
        /// Which media.
        media: Digest,
        /// Which tick of it.
        tick: i64,
        /// What the result is.
        description: FrameDescription,
    },
    /// A frame at a fraction of its opacity.
    ///
    /// Every channel, coverage included: in premultiplied form the colour has
    /// already been multiplied by the coverage, so halving one means halving
    /// the other. Anything else leaves a frame claiming more colour than its
    /// coverage allows, which [`crate::over`] refuses and is right to.
    Fade {
        /// What to fade.
        input: NodeId,
        /// How much of it is showing.
        opacity: Rational,
    },
    /// A frame with everything outside a shape taken away.
    ///
    /// The corners are fractions of the frame, so the node is the same node at
    /// every size — which is what lets a proxy render and a finish render
    /// share a cache key for everything above the mask.
    Mask {
        /// What to mask.
        input: NodeId,
        /// The shape, in fractions of the frame.
        corners: alloc::vec::Vec<(Rational, Rational)>,
        /// Whether what is kept is what lies outside it.
        inverted: bool,
    },
    /// A frame revealed behind a wipe's edge.
    ///
    /// [`Node::Fade`] with a different opacity at every pixel, which is what a
    /// wipe is. The edge's *position* is carried rather than the coverage
    /// plane it produces: four rationals hash into a node's identity and a
    /// plane of a million bytes would too, at a million times the cost, for a
    /// value that is a pure function of them and the frame's own size.
    Wipe {
        /// What to reveal.
        input: NodeId,
        /// How much of the direction runs across the picture.
        across: Rational,
        /// How much of it runs down.
        down: Rational,
        /// How far along its travel the edge is.
        fraction: Rational,
        /// How much of that travel the edge fades over.
        softness: Rational,
    },
    /// A frame with its coverage associated the other way.
    ///
    /// Premultiplying or dividing back out, named as its own step because
    /// [`Node::Convert`] refuses to do it: gaining, losing and re-associating
    /// alpha are three operations with three names, and a colour conversion
    /// that quietly performed one is the reason a keyed title arrives opaque.
    ///
    /// It exists because a look and a composite want opposite things. `over`
    /// is only correct on premultiplied samples; a lookup table is a
    /// non-linear function and on premultiplied samples computes `f(ac)` where
    /// `a·f(c)` was wanted. So a graded layer is fetched straight, graded, and
    /// associated here — which loses nothing, because the frame was never
    /// premultiplied to begin with.
    Associate {
        /// What to re-associate.
        input: NodeId,
        /// What the result is, which differs from the input only in how its
        /// coverage is carried.
        target: FrameDescription,
    },
    /// A frame with a look applied.
    ///
    /// The look is named by its digest rather than carried, because a cube is
    /// 35,937 triples and a graph is rebuilt for every instant. That also
    /// makes the node's identity depend on what the look *is*: a grade edited
    /// between two renders is a different key rather than a stale hit.
    Look {
        /// What to grade.
        input: NodeId,
        /// Which look.
        look: Digest,
    },
    /// One frame over another.
    ///
    /// The two are stored in one array rather than as two named fields so that
    /// [`Node::inputs`] can hand back a slice of *both*. A version that
    /// returned only one of them would let a cycle through the other slip past
    /// the check that makes cycles unrepresentable — the whole point of that
    /// check being that it needs nobody to remember it.
    Over {
        /// What is underneath, then what goes on top.
        layers: [NodeId; 2],
    },
    /// A frame in another description.
    Convert {
        /// Where the picture comes from.
        input: NodeId,
        /// What the result is.
        target: FrameDescription,
    },
}

impl Node {
    /// What this node produces, without producing it — where it can say.
    ///
    /// A fade and an `over` produce whatever their inputs are described as, so
    /// they cannot answer on their own. [`Graph::description`] can, because it
    /// can follow the edge.
    #[must_use]
    pub const fn description(&self) -> Option<FrameDescription> {
        match self {
            Self::Pattern { description, .. }
            | Self::Blank { description }
            | Self::Source { description, .. } => Some(*description),
            Self::Convert { target, .. } | Self::Associate { target, .. } => Some(*target),
            Self::Fade { .. }
            | Self::Wipe { .. }
            | Self::Mask { .. }
            | Self::Over { .. }
            | Self::Look { .. } => None,
        }
    }

    /// The nodes this one reads.
    #[must_use]
    pub fn inputs(&self) -> &[NodeId] {
        match self {
            Self::Pattern { .. } | Self::Blank { .. } | Self::Source { .. } => &[],
            Self::Convert { input, .. }
            | Self::Fade { input, .. }
            | Self::Wipe { input, .. }
            | Self::Mask { input, .. }
            | Self::Look { input, .. }
            | Self::Associate { input, .. } => core::slice::from_ref(input),
            Self::Over { layers } => layers.as_slice(),
        }
    }
}

/// Where the things a graph names by digest come from.
///
/// A graph knows how to combine frames and nothing about where anything lives.
/// Decoding, reading, waiting and caching a file's own structure all sit behind
/// this, and none of it is the graph's business.
///
/// Two methods, because there are two kinds of heavy thing a graph refers to
/// without holding: frames of media, and lookup tables. Both are named by
/// content digest rather than by a handle, so the same footage or the same
/// grade in two projects is one cached thing, and a file swapped underneath is
/// a different key rather than a stale hit.
pub trait Library {
    /// The frame at `tick` of the media with this content digest.
    ///
    /// # Errors
    ///
    /// Whatever the source cannot do.
    fn frame(&mut self, media: Digest, tick: i64, description: FrameDescription) -> Result<Frame>;

    /// Whether this media can be read at all.
    ///
    /// Asked *before* a graph is built rather than discovered while evaluating
    /// one, and that is the whole reason it exists as a separate question.
    ///
    /// A source node's identity is a digest over the media, the tick and the
    /// description — and **not** over whether the bytes happened to be
    /// reachable. So a node that quietly fell back to a slate when a file was
    /// missing would put that slate in the cache under the key of the real
    /// picture, and hand it back after the drive was plugged in again. That is
    /// exactly the staleness a content-addressed cache exists to prevent, and
    /// it is why the decision belongs to whatever plans the graph.
    ///
    /// The default is `true`: a library that cannot tell is a library that
    /// should try, and failing at `frame` is a worse answer than refusing to
    /// plan.
    fn available(&mut self, media: Digest) -> bool {
        let _ = media;
        true
    }

    /// The look with this digest.
    ///
    /// A cube is 35,937 triples and a graph is rebuilt for every instant, so a
    /// node names a look by what it *is* and fetches it from here — the same
    /// bargain as media, for the same reasons. A default is deliberately not
    /// provided: an implementor that renders graded material and forgot to
    /// write this should fail to compile rather than refuse at run time.
    ///
    /// # Errors
    ///
    /// Whatever the library cannot do.
    fn look(&mut self, look: Digest) -> Result<crate::look::Look>;
}

/// A graph of render steps.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Graph {
    nodes: Vec<Node>,
    identities: Vec<Digest>,
}

impl Graph {
    /// An empty graph.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            nodes: Vec::new(),
            identities: Vec::new(),
        }
    }

    /// How many nodes there are.
    #[must_use]
    pub fn len(&self) -> usize {
        self.nodes.len()
    }

    /// Whether the graph holds nothing.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }

    /// One node.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`] if the identifier names nothing.
    pub fn node(&self, id: NodeId) -> Result<&Node> {
        self.nodes.get(id.0).ok_or(RenderStatus::UnknownNode)
    }

    /// Add a node, and return the identifier that names it.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`] if the node refers to one that does not
    /// exist yet — which is the only way a cycle could be written, and it is
    /// refused here rather than found by a validation pass later.
    /// [`RenderStatus::GraphTooLarge`] past the policy bound.
    pub fn add(&mut self, node: Node) -> Result<NodeId> {
        for input in node.inputs() {
            if input.0 >= self.nodes.len() {
                return Err(RenderStatus::UnknownNode);
            }
        }
        if self.nodes.len() >= MAX_NODES {
            return Err(RenderStatus::GraphTooLarge);
        }
        let identity = self.identity_of(&node)?;
        self.nodes
            .try_reserve(1)
            .map_err(|_| RenderStatus::OutOfMemory)?;
        self.identities
            .try_reserve(1)
            .map_err(|_| RenderStatus::OutOfMemory)?;
        let id = NodeId(self.nodes.len());
        self.nodes.push(node);
        self.identities.push(identity);
        Ok(id)
    }

    /// What a node is, as a digest over its kind, its parameters and the
    /// identities of everything it reads.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`].
    pub fn identity(&self, id: NodeId) -> Result<Digest> {
        self.identities
            .get(id.0)
            .copied()
            .ok_or(RenderStatus::UnknownNode)
    }

    /// The cache key a node's result is stored under.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`].
    pub fn cache_key(&self, id: NodeId) -> Result<CacheKey> {
        Ok(CacheKey::current(&[self.identity(id)?], b"render-graph"))
    }

    /// Compute a node's identity from its parts.
    fn identity_of(&self, node: &Node) -> Result<Digest> {
        let mut hasher = Sha256::new();
        hasher.update(b"sapstudio-render-node-v1");
        match node {
            Node::Pattern {
                pattern,
                description,
            } => {
                hasher.update(&[1]);
                absorb_pattern(&mut hasher, *pattern);
                absorb_description(&mut hasher, *description);
            }
            Node::Blank { description } => {
                hasher.update(&[2]);
                absorb_description(&mut hasher, *description);
            }
            Node::Convert { input, target } => {
                hasher.update(&[3]);
                hasher.update(self.identity(*input)?.bytes());
                absorb_description(&mut hasher, *target);
            }
            Node::Source {
                media,
                tick,
                description,
            } => {
                hasher.update(&[4]);
                hasher.update(media.bytes());
                hasher.update(&tick.to_le_bytes());
                absorb_description(&mut hasher, *description);
            }
            Node::Fade { input, opacity } => {
                hasher.update(&[5]);
                hasher.update(self.identity(*input)?.bytes());
                hasher.update(&opacity.numerator().to_le_bytes());
                hasher.update(&opacity.denominator().to_le_bytes());
            }
            Node::Wipe {
                input,
                across,
                down,
                fraction,
                softness,
            } => {
                hasher.update(&[9]);
                hasher.update(self.identity(*input)?.bytes());
                for held in [across, down, fraction, softness] {
                    hasher.update(&held.numerator().to_le_bytes());
                    hasher.update(&held.denominator().to_le_bytes());
                }
            }
            Node::Mask {
                input,
                corners,
                inverted,
            } => {
                hasher.update(&[10]);
                hasher.update(self.identity(*input)?.bytes());
                hasher.update(&[u8::from(*inverted)]);
                for corner in corners {
                    for held in [corner.0, corner.1] {
                        hasher.update(&held.numerator().to_le_bytes());
                        hasher.update(&held.denominator().to_le_bytes());
                    }
                }
            }
            Node::Associate { input, target } => {
                hasher.update(&[8]);
                hasher.update(self.identity(*input)?.bytes());
                absorb_description(&mut hasher, *target);
            }
            Node::Look { input, look } => {
                hasher.update(&[7]);
                hasher.update(self.identity(*input)?.bytes());
                hasher.update(look.bytes());
            }
            Node::Over { layers } => {
                hasher.update(&[6]);
                for layer in layers {
                    hasher.update(self.identity(*layer)?.bytes());
                }
            }
        }
        Ok(hasher.finish())
    }

    /// What a node produces, following the edges where the node cannot say.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`].
    pub fn description(&self, id: NodeId) -> Result<FrameDescription> {
        let node = self.node(id)?.clone();
        let Some(description) = node.description() else {
            // A fade and an `over` produce whatever their inputs are described
            // as, so follow the first edge. Every input of those two carries
            // the same description — `over` refuses two that differ — so the
            // first one answers for all of them.
            let input = *node.inputs().first().ok_or(RenderStatus::UnknownNode)?;
            return self.description(input);
        };
        Ok(description)
    }

    /// Evaluate one node, using and filling a pool.
    ///
    /// Evaluation is bottom-up over the node's own inputs, which are all
    /// earlier in the graph, so no recursion can run away and no visited set
    /// is needed.
    ///
    /// The pool is what makes this worth building a graph for rather than
    /// calling the operations directly: a node's key is a digest over its
    /// kind, its parameters and its inputs' identities, so a frame that two
    /// parts of a render both need is fetched and computed once. That matters
    /// most for [`Node::Source`], where the cost is a decode.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`], or any refusal from the work itself.
    pub fn evaluate(
        &self,
        id: NodeId,
        pool: &mut FramePool,
        library: &mut dyn Library,
    ) -> Result<Frame> {
        if let Some(frame) = pool.get(self.cache_key(id)?) {
            return Ok(frame.clone());
        }
        let node = self.node(id)?.clone();
        let frame = match node {
            Node::Pattern {
                pattern,
                description,
            } => pattern.render(description).map_err(RenderStatus::Media)?,
            Node::Blank { description } => {
                Frame::blank(description).map_err(RenderStatus::Media)?
            }
            Node::Convert { input, target } => {
                let source = self.evaluate(input, pool, library)?;
                convert::convert(&source, target)?
            }
            Node::Source {
                media: which,
                tick,
                description,
            } => {
                let frame = library.frame(which, tick, description)?;
                if *frame.description() != description {
                    // A source that answers with something other than what it
                    // was asked for has answered a different question, and
                    // converting it here would be a decision made in the wrong
                    // place — `Convert` is a node, with a name (R-1.3).
                    return Err(RenderStatus::SourceDescriptionMismatch);
                }
                frame
            }
            Node::Fade { input, opacity } => {
                let source = self.evaluate(input, pool, library)?;
                composite::faded(&source, opacity)?
            }
            Node::Wipe {
                input,
                across,
                down,
                fraction,
                softness,
            } => {
                let source = self.evaluate(input, pool, library)?;
                let geometry = source.description().geometry();
                let width =
                    usize::try_from(geometry.width()).map_err(|_| RenderStatus::OutsideDomain)?;
                let height =
                    usize::try_from(geometry.height()).map_err(|_| RenderStatus::OutsideDomain)?;
                let coverage =
                    crate::shape::feathered(across, down, fraction, softness, width, height)?;
                composite::masked(&source, &coverage)?
            }
            Node::Mask {
                input,
                corners,
                inverted,
            } => {
                let source = self.evaluate(input, pool, library)?;
                let geometry = source.description().geometry();
                let width =
                    usize::try_from(geometry.width()).map_err(|_| RenderStatus::OutsideDomain)?;
                let height =
                    usize::try_from(geometry.height()).map_err(|_| RenderStatus::OutsideDomain)?;
                let coverage = crate::shape::masking(&corners, inverted, width, height)?;
                composite::masked(&source, &coverage)?
            }
            Node::Associate { input, target } => {
                let source = self.evaluate(input, pool, library)?;
                match (source.description().alpha(), target.alpha()) {
                    (Some(AlphaState::Straight), Some(AlphaState::Premultiplied)) => {
                        composite::premultiply(&source)?
                    }
                    (Some(AlphaState::Premultiplied), Some(AlphaState::Straight)) => {
                        composite::unpremultiply(&source)?
                    }
                    // Anything else is not a re-association: it is a frame
                    // with no coverage, or a node claiming to change something
                    // it is not changing.
                    _ => return Err(RenderStatus::WrongAlphaState),
                }
            }
            Node::Look { input, look } => {
                let source = self.evaluate(input, pool, library)?;
                library.look(look)?.apply(&source)?
            }
            Node::Over { layers } => {
                let bottom = self.evaluate(layers[0], pool, library)?;
                let top = self.evaluate(layers[1], pool, library)?;
                composite::over(&top, &bottom)?
            }
        };
        // A frame too large for the pool is still a correct result; it simply
        // is not kept. Refusing the render because the cache is small would be
        // the cache making a decision that is not its to make.
        match pool.insert(self.cache_key(id)?, frame.clone()) {
            Ok(()) | Err(sapstudio_media::MediaStatus::FrameLargerThanPool) => Ok(frame),
            Err(status) => Err(RenderStatus::Media(status)),
        }
    }
}

/// Absorb a pattern's identity into a hash.
fn absorb_pattern(hasher: &mut Sha256, pattern: TestPattern) {
    match pattern {
        TestPattern::Bars => hasher.update(&[1]),
        TestPattern::Ramp => hasher.update(&[2]),
        TestPattern::Checkerboard { square } => {
            hasher.update(&[3]);
            hasher.update(&square.to_le_bytes());
        }
        TestPattern::Flat { value } => {
            hasher.update(&[4, value]);
        }
        TestPattern::Offline => hasher.update(&[5]),
    }
}

/// Absorb a description's identity into a hash.
fn absorb_description(hasher: &mut Sha256, description: FrameDescription) {
    hasher.update(&description.geometry().width().to_le_bytes());
    hasher.update(&description.geometry().height().to_le_bytes());
    hasher.update(&description.pixel_aspect().numerator().to_le_bytes());
    hasher.update(&description.pixel_aspect().denominator().to_le_bytes());
    // The format and the colour go in through the frame's own tagging, which
    // already has stable numbers for them: a blank frame of this description
    // is a value whose digest covers exactly these things.
    match Frame::blank(description) {
        Ok(frame) => hasher.update(frame.digest().bytes()),
        Err(_) => hasher.update(b"undescribable"),
    }
}

/// The description a colour conversion of a node would produce, for callers
/// building a graph who want to check before they add.
#[must_use]
pub fn converted_description(
    source: FrameDescription,
    colour: ColourDescription,
) -> Option<FrameDescription> {
    FrameDescription::new(
        source.geometry(),
        source.format(),
        colour,
        source.siting(),
        source.alpha(),
        source.pixel_aspect(),
    )
    .ok()
}
